"""empty message

Revision ID: 8c001b44372b
Revises: 
Create Date: 2023-06-02 21:08:22.998370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c001b44372b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bed_persons', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_room_types_bed_persons'), ['bed_persons'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_types_bed_persons'))
        batch_op.drop_column('bed_persons')

    # ### end Alembic commands ###
